apiVersion: apps/v1
kind: Deployment
metadata:
  name: memos
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: memos
  template:
    metadata:
      labels:
        app: memos
    spec:
      containers:
        - name: memos
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - containerPort: {{ .Values.containerPort }}
         env:
            - name: MEMOS_PORT
              value: "{{ .Values.containerPort }}"
            - name: MEMOS_ADDR
              value: "0.0.0.0"