apiVersion: v1
kind: Service
metadata:
  name: memos
spec:
  type: {{ .Values.service.type | quote }}
  selector:
    app: memos
  ports:
    - name: http
      port: {{ .Values.service.port }}
      targetPort: {{ .Values.containerPort }}